---
- name: Check if 'Acronis' service is active
  systemd:
    name: acronis_mms.service
    state: started
  register: acronis_status
  ignore_errors: true

- name: Set fact if 'Acronis' service is running
  set_fact:
    acronis_installed: "{{ (acronis_status is defined)
      and (not acronis_status.failed | default(true))
      and (acronis_status.status is defined)
      and (acronis_status.status.ActiveState == 'active')
      }}"

- name: Print the result
  debug:
    msg: "Acronis service installed:  {{ acronis_installed }}"

- name: Download the package if it is not exist
  copy:
    src: /data/projects/exa_assets/CyberProtect_AgentForLinux_x86_64.bin
    dest: /root
    mode: "0755"
  when: not acronis_installed

- name: Make 'Acronis' installer executable
  file:
    path: /root/CyberProtect_AgentForLinux_x86_64.bin
    mode: "0750"
  when: not acronis_installed

- name: Run the installer script
  command: screen -dmS acronis bash -c "/root/CyberProtect_AgentForLinux_x86_64.bin"
  when: not acronis_installed

- name: Create exabackup directories for system and accounts
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /home/exabackup/system
    - /home/exabackup/accounts

- name: Copy the pre-backup-script
  copy:
    src: files/acronis/pre-backup-script
    dest: /home/exabackup
    mode: "0750"
