---
- name: Gather RPM facts
  package_facts:

- name: Check if cPanel is installed
  set_fact:
    csf_installed: "{{ ansible_facts.packages['csf'] is defined }}"

- name: Print the result
  debug:
    msg: "Are is CSF Installed ?  {{ csf_installed }}"

- name: Download CSF archive
  get_url:
    url: "https://download.configserver.com/csf.tgz"
    dest: "/tmp/csf.tgz"
  when: not csf_installed

- name: Untar CSF archive
  unarchive:
    src: "/tmp/csf.tgz"
    dest: "/tmp/"
    remote_src: yes
  when: not csf_installed

- name: Change to CSF directory and install CSF
  command:
    cmd: "bash install.sh"
    chdir: "/tmp/csf"
  when: not csf_installed
