---
- name: Check if CSF service is active
  systemd:
    name: csf.service
    state: started
  register: csf_status
  ignore_errors: true

- name: Set fact if CSF service is running
  set_fact:
    csf_installed: "{{ (csf_status is defined)
      and (not csf_status.failed | default(true))
      and (csf_status.status is defined)
      and (csf_status.status.ActiveState == 'active')
      }}"

- name: Print the result
  debug:
    msg: "CSF service installed:  {{ csf_installed }}"

- name: Download CSF archive
  get_url:
    url: "https://download.configserver.com/csf.tgz"
    dest: "/tmp/csf.tgz"
  when: not csf_installed

- name: Untar CSF archive
  unarchive:
    src: "/tmp/csf.tgz"
    dest: "/tmp/"
    remote_src: yes
  when: not csf_installed

- name: Change to CSF directory and install CSF
  command:
    cmd: "sudo bash install.sh"
    chdir: "/tmp/csf"
  when: not csf_installed

- name: Change 'lfd will not start while this is enabled' in csf.conf file
  become: true
  become_user: root
  lineinfile:
    path: /etc/csf/csf.conf
    regexp: '^TESTING = "1"'
    line: 'TESTING = "0"'
    create: yes
    backup: yes

- name: Add allowed ports in 'csf.conf' file
  become: true
  become_user: root
  lineinfile:
    path: /etc/csf/csf.conf
    regexp: "^{{ item.key }} = "
    line: '{{ item.key }} = "{{ item.value }}"'
    create: yes
    backup: yes
  loop:
    - {
        key: "TCP_IN",
        value: "20,21,22,25,26,53,80,110,143,443,465,587,993,3260,995,2077,2078,2079,2080,2082,2083,2086,2087,2095,2096,8443,2662,31262,5666,9101,9102,9103",
      }
    - {
        key: "TCP_OUT",
        value: "20,21,22,25,26,53,80,110,143,443,465,587,993,3260,995,2077,2078,2079,2080,2082,2083,2086,2087,2095,2096,8443,2662,31262,5666,9101,9102,9103",
      }
  when: not prof_mgmt | bool

- name: Add allowed Acronis ports in 'csf.conf' file
  become: true
  become_user: root
  lineinfile:
    path: /etc/csf/csf.conf
    regexp: "^{{ item.key }} = "
    line: '{{ item.key }} = "{{ item.value }}"'
    create: yes
    backup: yes
  loop:
    - {
        key: "TCP_IN",
        value: "20,21,22,25,26,53,80,110,143,443,465,587,993,3260,7770,7800,9851,44445,55556,7779,7778,9850,995,2077,2078,2079,2080,2082,2083,2086,2087,2095,2096,8443,2662,31262,5666,54741,52460,9101,9102,9103,49152:65534,9772,30800,30801,2600,2600,31009,2700,6110,30000:65535,8081",
      }
    - {
        key: "TCP_OUT",
        value: "20,21,22,25,37,43,53,80,110,113,443,587,853,873,993,995,2086,2087,2089,2703,25001,6109,7780,7755,7756,7765,9852,9860,9862,9876,9877,9850,9851,902,44445,55556,9772,30800,30801,2600,2600,2700,6110,30000:65535,9100,7074,7075,7077,31009,8081",
      }
  when: prof_mgmt | bool

- name: Add monitoring and backup servers to CSF allow list
  command: sudo csf -a {{ item.ip }} {{ item.comment }}
  loop:
    - { ip: "85.17.194.5", comment: "exa-vpn" }
    - { ip: "94.75.230.111", comment: "exa-opsview-server" }
    - { ip: "212.83.154.138", comment: "exa-bareos-server" }

- name: Restart CSF
  command: sudo csf -r

- name: Restart CSF using systemd
  become: true
  become_user: root
  service:
    name: csf
    state: restarted
    enabled: yes

- name: Restart LFD using systemd
  become: true
  become_user: root
  service:
    name: lfd
    state: restarted
    enabled: yes
