---
- name: Complete Server Setup
  hosts: managed-hosts
  gather_facts: true

  pre_tasks:
    - name: Identify Linux distribution
      set_fact:
        linux_distribution: "{{ ansible_facts['distribution'] | lower }}"
    - name: Print Linux distribution
      debug:
        msg: "This system is running {{ linux_distribution }} Dist"

  roles:
    - user_setup
    - role: common
      become: true
      remote_user: exadmn
    - role: opsview
      become: true
      remote_user: exadmn
    - role: backup
      become: true
      remote_user: exadmn
    - role: security
      become: true
      become_user: exadmn
