---
- name: Complete Server Setup
  hosts: managed_hosts
  gather_facts: true
  vars:
    awx_token: "{{ AWX_API_TOKEN }}"

  pre_tasks:
    - name: Identify Linux distribution
      set_fact:
        linux_distribution: "{{ ansible_facts['distribution'] | lower }}"
        linux_version: "{{ ansible_distribution_major_version }}"
    - name: Print Linux distribution and version
      debug:
        msg: "This system is running {{ linux_distribution }} version {{ linux_version }}"

  roles:
    - role: user_setup
      become: true
    - role: common
      become: true
      remote_user: exadmn
    - role: opsview
      become: true
      remote_user: exadmn
    - role: security
      become: true
      remote_user: exadmn
    - role: backup
      become: true
      remote_user: exadmn
