---
- name: Complete Server Setup
  hosts: managed_hosts
  gather_facts: true

  pre_tasks:
    - name: Identify Linux distribution
      set_fact:
        linux_distribution: "{{ ansible_facts['distribution'] | lower }}"
        linux_version: "{{ ansible_distribution_major_version }}"
    - name: Print Linux distribution and version
      debug:
        msg: "This system is running {{ linux_distribution }} version {{ linux_version }}"

    - name: Detect SSH Port
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        timeout: 5
      register: port_check
      ignore_errors: true

    - name: Set new SSH port
      set_fact:
        ansible_port: 31262
      when: not port_check.failed

  roles:
    - role: user_setup
      become: true
    - role: common
      become: true
      remote_user: exadmn
    - role: opsview
      become: true
      remote_user: exadmn
    - role: security
      become: true
      remote_user: exadmn
    - role: backup
      become: true
      remote_user: exadmn
