---
- name: Check if cPanel service is active
  systemd:
    name: cpanel.service
    state: started
  register: cpanel_status
  ignore_errors: true

- name: Set fact if cPanel service is running
  set_fact:
    cpanel_installed: "{{ (cpanel_status is defined)
      and (not cpanel_status.failed | default(true))
      and (cpanel_status.status is defined)
      and (cpanel_status.status.ActiveState == 'active')
      }}"

- name: Print the result
  debug:
    msg: "cPanel service installed:  {{ cpanel_installed }}"

- name: Include CSF firewall role if cPanel is installed
  include_role:
    name: security/firewall/csf
  when: cpanel_installed

- name: Include iptables firewall role if cPanel is not installed
  include_role:
    name: security/firewall/firewalld
  when:
    - not cpanel_installed
    - linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

- name: Include ufw firewall role if cPanel is not installed
  include_role:
    name: security/firewall/ufw
  when:
    - not cpanel_installed
    - linux_distribution == 'ubuntu'

- name: Include the 'Maldetect Antiviruses' role
  include_role:
    name: security/antiviruses/maldetect
  when: not prof_mgmt | bool

- name: Include the 'BitDefender Antiviruses' role
  include_role:
    name: security/antiviruses/bitdefender
  when: prof_mgmt | bool

- name: Include the 'Basic' role
  include_role:
    name: security/basic
