---
- name: Check if cPanel service is active
  systemd:
    name: cpanel.service
    state: started
  register: cpanel_status
  ignore_errors: true

- name: Set fact if cPanel service is running
  set_fact:
    cpanel_installed: "{{ cpanel_status.state == 'started' }}"

- name: Print the result
  debug:
    msg: "Are is cPanel Installed ?  {{ cpanel_installed }}"

- name: Include CSF firewall role if cPanel is installed
  include_role:
    name: security/firewall/csf
  when: cpanel_installed

- name: Include iptables firewall role if cPanel is not installed
  include_role:
    name: security/firewall/iptables
  when: not cpanel_installed
