- name: Check If 'Opsview' already downloaded or not
  become: yes
  become_user: exadmn
  stat:
    path: /tmp/opsview-agent-rhel.rpm
  register: file_exist

- name: Download the package if it is not exist
  become: yes
  become_user: exadmn
  get_url:
    url: https://box119.exaservers.com/exa_ansible/opsview-agent-rhel.rpm
    dest: /tmp/opsview-agent-rhel.rpm
  when: not file_exist.stat.exists
