---
- name: Ensure the Ansible tmp directory exists with correct permissions
  file:
    path: "/home/exadmn/.ansible/tmp"
    state: directory
    mode: "0755"
    owner: exadmn
    group: exadmn

- name: Check If 'Opsview' already downloaded or not
  stat:
    path: /tmp/opsview-agent-rhel.rpm
  register: file_exist

- name: Download the package if it is not exist
  get_url:
    url: https://box119.exaservers.com/exa_ansible/opsview-agent-rhel.rpm
    dest: /tmp/opsview-agent-rhel.rpm
  when: not file_exist.stat.exists

- name: Gather RPM facts
  rpm_facts:

- name: Check if opsview-agent is installed
  set_fact:
    opsview_installed: "{{ ansible_facts.packages['opsview-agent'] is defined }}"

- name: Install 'Opsview' RPM package if not installed
  command: sudo rpm -i /tmp/opsview-agent-rhel.rpm
  args:
    creates: /opt/opsview/agent
  when: not opsview_installed
