---
- name: First stage of the backup process - Registration
  include_role:
    name: backup/bareos/registration

- name: Second stage of the backup process - Configuration
  include_role:
    name: backup/bareos/configuration

- name: Make it Professional by installing Acronis
  include_role:
    name: backup/acronis
