---
- name: Ensure bind-address is set in MySQL config
  become: true
  lineinfile:
    path: /etc/my.cnf
    regexp: "^bind-address"
    line: "bind-address=127.0.0.1"
    create: yes
    backup: yes
  notify: Restart MySQL Service

- name: Set server contact email
  command: /usr/local/cpanel/bin/whmapi1 backup_config_set backupenable=1 backup_daily_enable=1 backup_daily_retention=1 backupdays="0,1,2,3,4,5,6" backup_weekly_enable=1 backup_weekly_day=5 backup_weekly_retention=1 backupaccts=1 mysqlbackup=both backuptype=incremental backupdir=/backup
