#!/bin/bash

if [ -d /etc/csf ]; then
   if [[ "$(sudo csf --status | grep DROP -c)" -gt 0 ]]; then
      if ! systemctl is-active --quiet lfd; then
               echo "CSF WARNING: CSF is Running but LFD is Stopped"
               exit 1
      fi
        echo "CSF OK: Running and LFD OK: Running"
        exit 0
   else
       echo "CSF CRITICAL: CSF NOT Running"
       exit 2
   fi
else
   echo "CSF CRITICAL: CSF NOT installed"
   exit 2
fi

