---
- name: Allow SSH on custom port via SELinux
  become: true
  command: semanage port -a -t ssh_port_t -p tcp {{ ssh_port }}
  when: linux_version == '9'

- name: Ensure root login is enabled in SSH config
  become: true
  become_user: root
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin yes"
    create: yes
    backup: yes
  notify: Restart SSH Service

- name: Ensure SSH port is set to our port
  become: true
  become_user: root
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?Port"
    line: "Port {{ ssh_port }}"
    create: yes
    backup: yes
  notify: Restart SSH Service

- name: Add Match User block for exadmn to sshd_config
  blockinfile:
    path: /etc/ssh/sshd_config
    marker: "# {mark} ANSIBLE MANAGED BLOCK: EXADMN RESTRICTIONS"
    block: |
      Match User exadmn
          PasswordAuthentication no
          AllowUsers exadmn@{{ ansible_control_ip }}
          PermitTTY no

- name: Set root password to same as ansible_password
  become: true
  become_user: root
  user:
    name: root
    password: "{{ ansible_password | password_hash('sha512') }}"
  when: linux_distribution == 'ubuntu'
