---
- name: Update MOTD
  copy:
    src: files/motd.txt
    dest: /etc/motd

- name: Install 'epel-release' prerequisite for vnstat package
  yum:
    name:
      - epel-release
    state: present
  when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

- name: Install 'compat-openssl11' prerequisite for opsview-agent package on RHEL based Linux 9 and above
  yum:
    name:
      - compat-openssl11
      - policycoreutils-python-utils
      - tar
      - ed
    state: present
    update_cache: yes
  when:
    - linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']
    - linux_version == '9'

- name: Install 'Useful' tools
  yum:
    name:
      - wget
      - rpcbind
      - perl
      - bind-utils
      - ksh
      - vnstat
      - iftop
      - ncdu
      - htop
      - inotify-tools
      - rkhunter
      - screen
    state: present
    update_cache: yes
  when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

- name: Install 'ed' tool
  yum:
    name:
      - ed
      - libstdc++.so.6
    state: present
    update_cache: yes
  when:
    - linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']
    - linux_version in ['8', '9']

- name: Install 'Useful' tools
  apt:
    name:
      - wget
      - vnstat
      - iftop
      - ncdu
      - htop
      - inotify-tools
      - rkhunter
      - screen
    state: present
    update_cache: yes
  when: linux_distribution == 'ubuntu'

- name: Ensure the 'Vnstat' service is started
  service:
    name: vnstat
    state: started
    enabled: yes
