- name: Update MOTD
  copy:
    src: files/motd.txt
    dest: /etc/motd

- name: Identify Linux distribution
  set_fact:
    linux_distribution: "{{ ansible_facts['distribution'] | lower }}"

- name: Update 'YUM' package cache
  become: true
  become_user: root
  yum:
    update_cache: yes
  when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

- name: Update APT package cache
  become: true
  become_user: root
  apt:
    update_cache: yes
  when: linux_distribution == 'ubuntu'

- name: Install 'epel-release' prerequisite for vnstat package
  become: yes
  become_user: root
  yum:
    name:
      - epel-release
    state: present
  when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

- name: Install 'Opsview' dependencies
  become: yes
  become_user: root
  yum:
    name:
      - wget
      - rpcbind
      - perl
      - bind-utils
      - ksh
      - vnstat
      - iftop
      - ncdu
      - htop
    state: present
  when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

- name: Install Opsview dependencies
  become: yes
  become_user: root
  apt:
    name:
      - wget
      - vnstat
      - iftop
      - ncdu
      - htop
    state: present
  when: linux_distribution == 'ubuntu'
