---
- name: Print Linux distribution
  debug:
    msg: "This system is running {{ linux_distribution }}"

- name: Update MOTD
  copy:
    src: files/motd.txt
    dest: /etc/motd

- name: Update 'YUM' package cache
  yum:
    update_cache: yes
  when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

- name: Update APT package cache
  apt:
    update_cache: yes
  when: linux_distribution == 'ubuntu'

- name: Install 'epel-release' prerequisite for vnstat package
  yum:
    name:
      - epel-release
    state: present
  when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

- name: Install 'Opsview' dependencies
  yum:
    name:
      - wget
      - rpcbind
      - perl
      - bind-utils
      - ksh
      - vnstat
      - iftop
      - ncdu
      - htop
    state: present
  when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

- name: Install Opsview dependencies
  apt:
    name:
      - wget
      - vnstat
      - iftop
      - ncdu
      - htop
    state: present
  when: linux_distribution == 'ubuntu'

- name: Ensure the 'Vnstat' service is started
  service:
    name: vnstat
    state: started
    enabled: yes
