---
- name: Ensure root login is enabled in SSH config
  become: true
  become_user: root
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin yes"
    create: yes
    backup: yes
  notify: Restart SSH Service

- name: Ensure SSH port is set to 31262
  become: true
  become_user: root
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?Port"
    line: "Port 31262"
    create: yes
    backup: yes
  notify: Restart SSH Service
