---
- name: Download and configure 'Bareos' repository for RHEL-based distros
  get_url:
    url: "https://download.bareos.org/current/EL_{{ linux_version }}/add_bareos_repositories.sh"
    dest: /tmp/add_bareos_repositories.sh
  when:
    - linux_distribution in ['centos', 'rocky', 'almaLinux', 'cloudLinux']
    - linux_version in ['7', '8', '9']

- name: Download and configure 'Bareos' repository for Ubuntu-based distros
  get_url:
    url: "https://download.bareos.org/current/xUbuntu_{{ linux_version }}.04/add_bareos_repositories.sh"
    dest: /tmp/add_bareos_repositories.sh
  when:
    - linux_distribution == 'ubuntu'
    - linux_version in ['20', '22', '24']
