---
- name: Check If 'Bareos Repo Script' already downloaded or not
  stat:
    path: /tmp/add_bareos_repositories.sh
  register: file_exist

- name: Debug variable values before Bareos repo download
  debug:
    msg:
      - "file_exist.stat.exists: {{ file_exist.stat.exists }}"
      - "linux_distribution: {{ linux_distribution }}"
      - "linux_version: {{ linux_version }}"

##########
# RHEL 7 #
##########

- name: Download bareos-common package for CentOS/CloudLinux 7
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  loop:
    - {
        url: "https://box119.exaservers.com/exa_ansible/bareos-common-19.2.7-2.el6.x86_64.rpm",
        dest: "/tmp/bareos-common.rpm",
      }
    - {
        url: "https://box119.exaservers.com/exa_ansible/bareos-filedaemon-19.2.7-2.el6.x86_64.rpm",
        dest: "/tmp/bareos-filedaemon.rpm",
      }
  when:
    - linux_distribution in ['centos', 'cloudlinux']
    - linux_version == '7'

- name: Install bareos-common directly on CentOS/CloudLinux 7
  yum:
    name:
      - /tmp/bareos-common.rpm
      - /tmp/bareos-filedaemon.rpm
  when:
    - linux_distribution in ['centos', 'cloudlinux']
    - linux_version == '7'

############
# RHEL 8,9 #
############

- name: Download and configure 'Bareos' repository for RHEL-based distros
  get_url:
    url: "https://download.bareos.org/current/EL_{{ linux_version }}/add_bareos_repositories.sh"
    dest: /tmp/add_bareos_repositories.sh
  when:
    - not file_exist.stat.exists
    - linux_distribution in ['centos', 'rocky', 'almalinux', 'cloudlinux']
    - linux_version in ['8', '9']

- name: Run the script to add the repository
  command: "sudo bash /tmp/add_bareos_repositories.sh"
  when:
    - linux_distribution in ['centos', 'rocky', 'almalinux', 'cloudlinux']
    - linux_version in ['8', '9']

- name: Install 'Bareos' File Daemon on RHEL-based distros
  yum:
    name: bareos-fd
    state: present
    update_cache: yes
  when:
    - linux_distribution in ['centos', 'rocky', 'almalinux', 'cloudLinux']
    - linux_version in ['8', '9']

##########
# Ubuntu #
##########

- name: Download and configure 'Bareos' repository for Ubuntu-based distros
  get_url:
    url: "https://download.bareos.org/current/xUbuntu_{{ linux_version }}.04/add_bareos_repositories.sh"
    dest: /tmp/add_bareos_repositories.sh
  when:
    - not file_exist.stat.exists
    - linux_distribution == 'ubuntu'
    - linux_version in ['20', '22', '24']

- name: Run the script to add the repository
  command: "sudo bash /tmp/add_bareos_repositories.sh"
  when:
    - linux_distribution == 'ubuntu'
    - linux_version in ['20', '22', '24']

- name: Install 'Bareos' File Daemon on Debian-based distros
  apt:
    name: bareos
    state: present
    update_cache: yes
  when: linux_distribution == 'ubuntu'

- name: Configure Bareos settings
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: bareos
    group: bareos
    mode: "0644"
  loop:
    - {
        src: "templates/bareos/myself.conf.j2",
        dest: "/etc/bareos/bareos-fd.d/client/myself.conf",
      }
    - {
        src: "templates/bareos/director.conf.j2",
        dest: "/etc/bareos/bareos-fd.d/director/bareos-dir.conf",
      }
  notify: Restart Bareos File-Daemon

- name: Download and extract 'TLS' files
  get_url:
    url: https://box119.exaservers.com/tls.tar.gz
    dest: /tmp/tls.tar.gz

- name: Extract 'TLS' files to 'Bareos' directory
  unarchive:
    src: /tmp/tls.tar.gz
    dest: /etc/bareos/
    remote_src: yes
  notify: Restart Bareos File-Daemon

- name: Set ownership of 'Bareos' directory
  file:
    path: /etc/bareos/
    owner: bareos
    group: bareos
    recurse: yes
  notify: Restart Bareos File-Daemon

- name: Set calculated cron days
  set_fact:
    before_backup: "{{ (backup_date | int) - 1 }}"
    after_backup: "{{ '5' if (backup_date | int) == 28 else (backup_date | int) + 5 }}"
  when: cpanel_installed

- name: Create backup cron job (before backup_date)
  cron:
    name: "Backup users without home directory"
    user: root
    minute: "0"
    hour: "0"
    day: "{{ before_backup }}"
    month: "*"
    weekday: "*"
    job: "for user in `ls /var/cpanel/users | grep -v '\\.'`; do /scripts/pkgacct --skiphomedir $user /home ; done"
  when: cpanel_installed

- name: Create cleanup cron job (after backup_date)
  cron:
    name: "Clean old cpmove backups"
    user: root
    minute: "0"
    hour: "0"
    day: "{{ after_backup }}"
    month: "*"
    weekday: "*"
    job: "find /home -type f -name 'cpmove-*' -exec rm -rf {} \\;"
  when: cpanel_installed
